export const GET_DATA_SALARY_SINGLE_EMPLOYEE_SUCCESS =
  "GET_DATA_SALARY_SINGLE_EMPLOYEE_SUCCESS";
export const GET_DATA_SALARY_SINGLE_EMPLOYEE_FAILURE =
  "GET_DATA_SALARY_SINGLE_EMPLOYEE_FAILURE";
