export const GET_DATA_SALARY_SUCCESS = "GET_DATA_SALARY_SUCCESS";
export const GET_DATA_SALARY_FAILURE = "GET_DATA_SALARY_FAILURE";
export const DELETE_DATA_SALARY_SUCCESS = "DELETE_DATA_SALARY_SUCCESS";
export const DELETE_DATA_SALARY_FAILURE = "DELETE_DATA_SALARY_FAILURE";
