export const GET_DATA_CUTTING_SUCCESS = "GET_DATA_CUTTING_SUCCESS";
export const GET_DATA_CUTTING_FAILURE = "GET_DATA_CUTTING_FAILURE";
export const CREATE_DATA_CUTTING_SUCCESS = "CREATE_DATA_CUTTING_SUCCESS";
export const CREATE_DATA_CUTTING_FAILURE = "CREATE_DATA_CUTTING_FAILURE";
export const UPDATE_DATA_CUTTING_SUCCESS = "UPDATE_DATA_CUTTING_SUCCESS";
export const UPDATE_DATA_CUTTING_FAILURE = "UPDATE_DATA_CUTTING_FAILURE";
export const DELETE_DATA_CUTTING_SUCCESS = "DELETE_DATA_CUTTING_SUCCESS";
export const DELETE_DATA_CUTTING_FAILURE = "DELETE_DATA_CUTTING_FAILURE";
