export const GET_DATA_EMPLOYEE_SUCCESS = "GET_DATA_EMPLOYEE_SUCCESS";
export const GET_DATA_EMPLOYEE_FAILURE = "GET_DATA_EMPLOYEE_FAILURE";
export const EMPLOYEE_IMAGE_SUCCESS = "EMPLOYEE_IMAGE_SUCCESS";
export const EMPLOYEE_IMAGE_FAILURE = "EMPLOYEE_IMAGE_FAILURE";
export const GET_DATA_EMPLOYEE_BY_ID_SUCCESS =
  "GET_DATA_EMPLOYEE_BY_ID_SUCCESS";
export const GET_DATA_EMPLOYEE_BY_ID_FAILURE =
  "GET_DATA_EMPLOYEE_BY_ID_FAILURE";
export const GET_DATA_EMPLOYEE_BY_NIK_SUCCESS =
  "GET_DATA_EMPLOYEE_BY_NIK_SUCCESS";
export const GET_DATA_EMPLOYEE_BY_NIK_FAILURE =
  "GET_DATA_EMPLOYEE_BY_NIK_FAILURE";
export const GET_DATA_EMPLOYEE_BY_NAME_SUCCESS =
  "GET_DATA_EMPLOYEE_BY_NAME_SUCCESS";
export const GET_DATA_EMPLOYEE_BY_NAME_FAILURE =
  "GET_DATA_EMPLOYEE_BY_NAME_FAILURE";
export const CREATE_DATA_EMPLOYEE_REQUEST = "CREATE_DATA_EMPLOYEE_REQUEST";
export const CREATE_DATA_EMPLOYEE_SUCCESS = "CREATE_DATA_EMPLOYEE_SUCCESS";
export const CREATE_DATA_EMPLOYEE_FAILURE = "CREATE_DATA_EMPLOYEE_FAILURE";
export const UPDATE_DATA_EMPLOYEE_SUCCESS = "UPDATE_DATA_EMPLOYEE_SUCCESS";
export const UPDATE_DATA_EMPLOYEE_FAILURE = "UPDATE_DATA_EMPLOYEE_FAILURE";
export const DELETE_DATA_EMPLOYEE_SUCCESS = "DELETE_DATA_EMPLOYEE_SUCCESS";
export const DELETE_DATA_EMPLOYEE_FAILURE = "DELETE_DATA_EMPLOYEE_FAILURE";
