export const GET_DATA_ATTENDANCE_SUCCESS = " GET_DATA_ATTENDANCE_SUCCESS";
export const GET_DATA_ATTENDANCE_FAILURE = " GET_DATA_ATTENDANCE_FAILURE";
export const CREATE_DATA_ATTENDANCE_SUCCESS = " CREATE_DATA_ATTENDANCE_SUCCESS";
export const CREATE_DATA_ATTENDANCE_FAILURE = "CREATE_DATA_ATTENDANCE_FAILURE";
export const UPDATE_DATA_ATTENDANCE_SUCCESS = " UPDATE_DATA_ATTENDANCE_SUCCESS";
export const UPDATE_DATA_ATTENDANCE_FAILURE = "UPDATE_DATA_ATTENDANCE_FAILURE";
export const DELETE_DATA_ATTENDANCE_SUCCESS = "DELETE_DATA_ATTENDANCE_SUCCESS";
export const DELETE_DATA_ATTENDANCE_FAILURE = "DELETE_DATA_ATTENDANCE_FAILURE";
