export const GET_DATA_DEPARTMENT_SUCCESS = "GET_DATA_DEPARTMENT_SUCCESS";
export const GET_DATA_DEPARTMENT_FAILURE = "GET_DATA_DEPARTMENT_FAILURE";
export const CREATE_DATA_DEPARTMENT_SUCCESS = "CREATE_DATA_DEPARTMENT_SUCCESS";
export const CREATE_DATA_DEPARTMENT_FAILURE = "CREATE_DATA_DEPARTMENT_FAILURE";
export const UPDATE_DATA_DEPARTMENT_SUCCESS = "UPDATE_DATA_DEPARTMENT_SUCCESS";
export const UPDATE_DATA_DEPARTMENT_FAILURE = "UPDATE_DATA_DEPARTMENT_FAILURE";
export const DELETE_DATA_DEPARTMENT_SUCCESS = "DELETE_DATA_DEPARTMENT_SUCCESS";
export const DELETE_DATA_DEPARTMENT_FAILURE = "DELETE_DATA_DEPARTMENT_FAILURE";
